# Generated by Django 5.0.6 on 2024-05-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField(blank=True)),
                ('precio', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('entrega', models.BooleanField(default=False)),
            ],
        ),
    ]
